### ISSUE TITLE
[Bug] Unable to find libappearancecell.dylib

### ISSUE THREAD

**Issue by nahtedetihw** [cbyrne/libappearancecell#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Information (please complete the following information):**
 - iOS Version: [e.g. 13.5]
 - Device [e.g. iPhone X, iPhone 11 Pro]
 - Jailbreak + Bootstrap [e.g. checkra1n (oddessyra1n), unc0ver (default)]

**Additional context**

**Comment by conorthedev** [comment]
Maybe don't keep the template not filled out.
The .dylib file can be found on your device on the path ``/usr/lib/libappearancecell.dylib``. Copy that to ``$THEOS/lib`` on your computer.
