### ISSUE TITLE
[Bug] Crash

### ISSUE THREAD

**Issue by nicho1asdev** [cbyrne/libappearancecell#4]
**Describe the bug**
If you haven't specified a notification the settings app crashes when selecting an option.

**To Reproduce**
1. Don't assign the key "PostNotificaition" in the root.plist file of the preference bundle.
2. Rebuild and install
3. Open the preference bundle and tap on an option.
4. Crash

**Expected behavior**
No crash if the PostNotification key isn't assigned.
**Device Information (please complete the following information):**
 - iOS Version: 13.5
 - Device: iPhone Xr
 - Jailbreak + Bootstrap: unc0ver (default)

**Comment by conorthedev** [comment]
It is recommended to have the PostNotificaition field, although I will make it non-optional. Will close when fix is merged into ``master``
