### ISSUE TITLE
[Bug] Multiple cells on one page don't save correctly

### ISSUE THREAD

**Issue by thatmarcel** [cbyrne/libappearancecell#5]
**Describe the bug**
When I put two cells on one page, they show and save the wrong values. Demo: https://streamable.com/lzpk0y

**To Reproduce**
Create a preference plist with two cells with different defaults keys and test it on a device

**Expected behavior**
The cells should show and save the correct values

**Device Information:**
 - iOS Version: 13.5
 - Device: iPhone Xs
 - Jailbreak + Bootstrap unc0ver (default)

**Comment by conorthedev** [comment]
Can you show me your plist file? This shouldn't be happening.

**Comment by conorthedev** [comment]
I am currently able to reproduce this issue. Fixing now
